export const FETCH_SHOPLIST_SUCCESS = 'FETCH_SHOPLIST_SUCCESS'
export const FETCH_SHOPLIST_ERROR = 'FETCH_SHOPLIST_ERROR'

export const SET_SHOPNAME_SELECTED = 'SET_SHOPNAME_SELECTED'
export const SET_SHOPINDEX_SELECTED = 'SET_SHOPINDEX_SELECTED'

export const SET_FROM_LOC_STORAGE_TO_BUSCKET = 'SET_FROM_LOC_STORAGE_TO_BUSCKET'
export const ADD_ITEM_TO_BUSCKET = 'ADD_ITEM_TO_BUSCKET'
export const REMOVE_ITEM_FROM_BASKET = 'REMOVE_ITEM_FROM_BASKET'
export const CHANGE_iTEM_AMOUNT = 'CHANGE_iTEM_AMOUNT'
export const CLEAR_ITEMS_FROM_BUSKET = 'CLEAR_ITEMS_FROM_BUSKET'

export const SET_BUSKET_SHOP_NAME = 'SET_BUSKET_SHOP_NAME'

export const SET_USER_ORDER_DATA = 'SET_USER_ORDER_DATA'
export const SET_USER_ORDER_NAME = 'SET_USER_ORDER_NAME'
export const SET_USER_ORDER_EMAIL = 'SET_USER_ORDER_EMAIL'
export const SET_USER_ORDER_PHONE = 'SET_USER_ORDER_PHONE'
export const SET_USER_ORDER_ADDRESS = 'SET_USER_ORDER_ADDRESS'

export const SET_HISTORY_SUCCESS = 'SET_HISTORY_SUCCESS'
export const SET_HISTORY_ERROR = 'SET_HISTORY_ERROR'
